name: Checks

on:
  pull_request:
    branches: 
      - 'master'

jobs:
  check-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: '3.8.3'

      - name: Build with Maven
        run: |
          cd backend/shop-floor-assistance-backend
          mvn clean verify
